let user = prompt ('Ismingizni kiritng')
alert (user)
let famiya = prompt ('Familyangizni kiriting')
alert (famiya)
let age = prompt ('Yoshingizni kiriting')
alert (age)
let subject = prompt ('Yoqtirgan fanizi yozing')
alert (subject)
let familya = prompt ('Familyangizni kiriting')
alert (famiya)
let location = prompt ('Yashaydigan tumaningizni kiriting')
alert (location)
let submit = ('malumotlarni kiritganiz uchun tashakkur')
alert (submit)